### ISSUE TITLE
My font-colors look very different compared to yours

### ISSUE THREAD

**Issue by crunchtime-ali** [philsinatra/macos-dark-mode-theme#1]
My font colors don't look like in your screenshots (VSCode 1.28.1) but like this:

<img width="482" alt="fonttest" src="https://user-images.githubusercontent.com/7140800/47427821-c929f500-d791-11e8-9fb0-571ff396c6cc.png">

Do you have a clue what is going wrong for me? I also tested this in VSCode 1.29.0-insider

**Comment by philsinatra** [comment]
The orange and pink shades have recently been updated to match recent updates from Apple. I have to update the screenshots in the README to match.

**Comment by crunchtime-ali** [comment]
tbh I don't like them nearly as much as the colours in your screenshots. Could you maybe offer an alternate color scheme for them?

Amazing work btw. This is one finely tuned theme.

**Comment by philsinatra** [comment]
Okay, I added both options to v0.2.0

- Dark Mode: the original theme you prefer
- Dark Mode Warm: the adjusted version based on recent Apple updates

**Comment by crunchtime-ali** [comment]
Awesome! Thanks a lot. I like the contrast better on the original one.
