### ISSUE TITLE
F# Interactive mode variables almost not visible

### ISSUE THREAD

**Issue by heyjoakim** [philsinatra/macos-dark-mode-theme#2]
Hi, In F# interactive mode vars and bool values are a dark blue / grey color which is almost not visible. Could you please change this.

![Screenshot from 2020-04-04 11-37-10](https://user-images.githubusercontent.com/43805989/78423727-bdba4900-7668-11ea-90cd-4121384bd661.png)

**Comment by philsinatra** [comment]
I'm not familiar with F# interactive mode. Is there a specific extension you're using to enable this mode? 

Can you tell me the scope of the vars and bools? 

1. Open the command palette <kbd>cmd|ctrl</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>
1. Type "scope" in the fuzzy search
1. Select "Developer: Inspect TM Scopes"
1. Tell me the scope information for the var keywords and boolean values

If you can tell me the scope of each, I'll be able to add color values for both to the theme.

**Comment by heyjoakim** [comment]
Thanks for taking your time to answer. Unfortunately it is not possible to use the "Developer: Inspect TM scopes" tool because it is not in the code, but in the terminal when f# is compiled. I use the "Ionide-fsharp" extension. But dont make a fuzz about fixing it, this theme is my favorite but I only use f# occasionally. Thanks anyway though.

![Screenshot from 2020-04-06 17-13-24](https://user-images.githubusercontent.com/43805989/78574193-f1909c80-7829-11ea-9d35-6ec1ebc400d6.png)
